# These are the global settings

---
global:
  canvas:
    course_id: 47355
  grading:
    max_grade: 10
  
  llm:
    model: "gpt-4o"
    grading_temperature: 0.0
    feedback_temperature: 1.0
    n_choices_grading: 1 
    n_choices_feedback: 1
    use_uva_openai: True
    prompts:
      grading: 
        system_prompt: "resources/llm_prompts/grading/system_prompt.txt"
        user_prompt: "resources/llm_prompts/grading/user_prompt.txt"
      feedback_questionwise: 
        system_prompt: "resources/llm_prompts/feedback_questionwise/system_prompt.txt"
        user_prompt: "resources/llm_prompts/feedback_questionwise/user_prompt.txt"
      feedback_summary: 
        system_prompt: "resources/llm_prompts/feedback_summary/system_prompt.txt"
        user_prompt: "resources/llm_prompts/feedback_summary/user_prompt.txt"
    
  paths:
    resources: "resources"
    submissions: "submissions"

assignments:
  1:
    canvas:
      assignment_id: 508875
      quiz_id: 101417
      r_quiz_question_id: 1205946
      adv_quiz_question_id: 1205946
    global_rubrics:
      - "Do not subtract points for typos in comments if it is clear the student understands the concept and provided a correct answer"
      - "Do not subtract points for using = instead of <- in R if the code is correct"
      - "Subtract 1 point if the student did not attempt the task."
    lock_grades_date: "2025-01-13"
 
  2:
    canvas:
      assignment_id: 508895
      quiz_id: 101425
      r_quiz_question_id: 1205979
      adv_quiz_question_id: 1205980
    global_rubrics:
      - "Do not subtract points for typos in comments if it is clear the student understands the concept and provided a correct answer"
      - "Do not subtract points for using = instead of <- in R if the code is correct"
      - "The student may have reused a plot they previously defined"
      - "Subtract 1 point if the student did not attempt the task."
    lock_grades_date: "2025-01-20"

  3:
    canvas:
      assignment_id: 508890 
      quiz_id: 101423
      r_quiz_question_id: 1205973
      adv_quiz_question_id: 1205974
    global_rubrics:
      - "Do not subtract points for typos in comments if it is clear the student understands the concept and provided a correct answer"
      - "Do not subtract points for using = instead of <- in R if the code is correct"
      - "Subtract 1 point if the student did not attempt the task."
    lock_grades_date: "2025-01-26"

  4:
    canvas:
      assignment_id: 508900
      quiz_id: 101427
      r_quiz_question_id: 1205986
      adv_quiz_question_id: 1205987
    global_rubrics:
      - "Do not subtract points for typos in comments if it is clear the student understands the concept and provided a correct answer"
      - "Do not subtract points for using = instead of <- in R if the code is correct"
      - "Subtract 1 point if the student did not attempt the task."
    lock_grades_date: "2025-02-06"



